#  ================= SQLite ========================================

default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3

production:
  <<: *default
  database: db/production.sqlite3


# ================== PostgreSQL ====================================
# default: &default
#   adapter: postgresql
#   encoding: unicode
#   # For details on connection pooling, see rails configuration guide
#   # http://guides.rubyonrails.org/configuring.html#database-pooling
#   pool: 5

# development:
#   <<: *default
#   database: nzt_development

# test:
#   <<: *default
#   database: nzt_test

# production:
#   <<: *default
#   database: nzt_production
#   username: nzt
#   password: <%= ENV['NZT_DATABASE_PASSWORD'] %>
# ======================= MYSQL ======================================
# development:
#   adapter: mysql2
#   encoding: utf8
#   reconnect: false
#   database: web_creator_development
#   pool: 5
#   username: root
#   password: tamir
#   host: localhost

# # Warning: The database defined as "test" will be erased and
# # re-generated from your development database when you run "rake".
# # Do not set this db to the same as development or production.
# test:
#   adapter: mysql2
#   encoding: utf8
#   reconnect: false
#   database: web_creator_test
#   pool: 5
#   username: root
#   password: tamir
#   host: localhost

# production:
#   adapter: mysql2
#   encoding: utf8
#   reconnect: false
#   database: web_creator_production
#   pool: 5
#   username: root
#   password: tamir
#   host: localhost
